### PR TITLE
feat: add check if version is latest

### PR DESCRIPTION
**Pull request by dblythy**
Currently, it's very easy to be looking at an outdated JS DOC page without knowing.

This script checks the URL version, then gets the latest SDK version from UNPKG. If it's outdated, it adds the following div to the screen:

Screen Shot 2022-05-28 at 8 46 39 pm

To make this backwards compatible however we would need to somehow edit all the files on the github pages ENV for the JS SDK and server SDK.

### CODE REVIEW

**Comment by dblythy** [comment]
@mtrezza let me know your thoughts

**Comment by mtrezza** [comment]
Is that forked template maintained at all? Maybe we just switch to a template that is more modern / maintained? 
I personally never found this to be a good template, it's difficult to navigate.

How about switching to this: https://github.com/ankitskvmdam/clean-jsdoc-theme
It's maintained, has dark mode and a foldable menu, much better in my view.
And we can delete this fork, one worry less.

I've opened https://github.com/parse-community/parse-server/issues/8017

--- 

Oh, I misread your suggestion - that is a nice feature indeed! But that doesn't change the fact that the template is outdated and causes a bad experience for developers.

**Comment by mtrezza** [comment]
I don't know how easily we can publish this package:
- on npm it's still 1.0.0
- here we already have 1.2.3 from 2017
- the package.json here is still 1.0.0
- its out of sync with the orignal repo which had commits in 2020
- there is no CI to publish, so this has to be published to npm manually

I'm not sure we want to touch this at the moment, it looks like a pandora's box and looks like quite a process to investigate. Maybe we should rather invest the time to switch to the new template?

**Comment by dblythy** [comment]
Sounds good to me!

**Pull request merged**
